config/routes.rb
WeddingApp::Application.routes.draw do

  root to: "static_pages#wedding"

  
  match '/wedding',     to: 'static_pages#wedding'
  match '/us',        	to: 'static_pages#us'
  match '/weddingday', 	to: 'static_pages#weddingday'
  match '/bridalparty', to: 'static_pages#bridalparty'
  match '/location', 	to: 'static_pages#location'
  match '/photos',      to: 'static_pages#photos'
  match '/registry',    to: 'static_pages#registry'
  match '/rsvp',  	to: 'rsvps#new'
  
  resources :rsvps, :only => [:new, :create] do
    get 'thank_you', :on => :collection
  end

end

app/models/rsvp.rb
class Rsvp
  extend ActiveModel::Naming
  include ActiveModel::Conversion
  include ActiveModel::Validations
  include ActionView::Helpers::TextHelper
  
  attr_accessor :firstname1, :lastname1, :no1, :yes1,
                :firstname2, :lastname2, :no2, :yes2,
                :firstname3, :lastname3, :no3, :yes3,
                :firstname4, :lastname4, :no4, :yes4,
                :firstname5, :lastname5, :no5, :yes5,
                :email, :phone, :notes, :nickname
  
  validates :firstname1,
            :presence => true

  validates :lastname1,
            :presence => true
  
  validates :email,
            :presence => true,
            :format => { :with => /\b[A-Z0-9._%a-z\-]+@(?:[A-Z0-9a-z\-]+\.)+[A-Za-z]{2,4}\z/ }
  
  validates :nickname,
            :format => { :with => /^$/ }
  
  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end
  
  def deliver
    return false unless valid?
    Pony.mail({
      :from => %("#{firstname1} #{lastname1}" <#{email}>),
      :reply_to => email,
      :subject => "Website RSVP",
      :body => "#{firstname1} #{lastname1} #{yes1} #{no1}",
      :html_body => simple_format(make_message)
    })
  end

  def make_message
    message = ""
    yes = [yes1, yes2, yes3, yes4, yes5]
    no = [no1, no2, no3, no4, no5]
    first = [firstname1, firstname2, firstname3, firstname4, firstname5]
    last = [lastname1, lastname2, lastname3, lastname4, lastname5]
    
    for n in 0..4
      guest = first[n]+ ' ' + last[n]
      if guest != ' '

        if yes[n] == '1'
          guest = guest + ' - accepted'
        end

        if no[n] == '1'
            guest = guest + ' - declined'
        end

        message = message + guest + "\n"
      end
    end
    message = message + 'Contact email: ' + email + "\n" + 'Phone: ' + phone + "\n" + notes

    return message
  end
  
  def persisted?
    false
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  email           :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  password_digest :string(255)
#

class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation
  has_secure_password

  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token
  
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                 uniqueness: { case_sensitive: false }   
  validates :password, presence: true, length: { minimum: 6 }   
  validates :password_confirmation, presence: true  
  
  private
    def create_remember_token
      self.remember_token = SecureRandom.hex
    end          
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/rsvps_controller.rb
class RsvpsController < ApplicationController

  def new
    @rsvp = Rsvp.new
  end
  
  def create
    @rsvp = Rsvp.new(params[:rsvp])
    if @rsvp.deliver
      flash[:success] = "Thank you for your RSVP! Please enjoy the rest of the website."
      redirect_to('/wedding.html')
      #render :thank_you
    else
      render :new
    end
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to user
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def us
  end

  def wedding
  end
  
  def bridalparty
  end
  
  def location
  end
  
  def photos
  end
  
  def registry
  end

  def rsvp
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the our Wedding Website!"
      redirect_to @user
    else
      render 'new'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Jessie & Jordan"
    if page_title.empty?
      base_title
    else
      "#{base_title} * #{page_title}"
    end
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end
  
  def signed_in?
    !current_user.nil?
  end
  
  def current_user=(user)
    @current_user = user
  end
  
  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end
  
  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
</head>
<body>
<div id="main-wrapper">
  <div id="titlebar">Jessie &amp; Jordan</div>
  
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
  
  <%= yield %>

  <%= debug(params) if Rails.env.development? %>
  
  <div id="navigation">
    <%= link_to "home", root_path %>
    <%= link_to "us", us_path %>
    <%= link_to "wedding", weddingday_path %>
    <%= link_to "bridal party", bridalparty_path %>
    <%= link_to "location", location_path %>
    <!--%= link_to "photos", photos_path %-->
    <%= link_to "registry", registry_path %>
    <%= link_to "RSVP", rsvp_path %>
  </div>

</div><!--from main wrapper>

      <%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/rsvps/_form.html.erb
<style>
td
{
vertical-align:middle;
}
</style>

<%= form_for rsvp do |f| %>
  <% if rsvp.errors.any? %>
    <ul>
      <% rsvp.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
  
  <div style="display: none;">
    <%= f.label :nickname %><br/>
    <%= f.text_field :nickname %>
  </div>
  <table cellpadding="5">
    <tr>
      <td width="75"></td>
      <td width="150">First Name</td>
      <td width="150">Last Name</td>
      <td width="100">Attending</td>
      <td width="200">Regretfully Decline</td>
    </tr>
    <tr>
      <td>Guest 1:</td>
      <td><%= f.text_field :firstname1, :size => "10" %></td>
      <td><%= f.text_field :lastname1, :size => "10" %></td>
      <td><%= f.check_box :yes1 %></td>
      <td><%= f.check_box :no1 %></td>
    </tr>
    <tr>
      <td>Guest 2:</td>
      <td><%= f.text_field :firstname2, :size => "10" %></td>
      <td><%= f.text_field :lastname2, :size => "10" %></td>
      <td><%= f.check_box :yes2 %></td>
      <td><%= f.check_box :no2 %></td>
    </tr>
    <tr>
      <td>Guest 3:</td>
      <td><%= f.text_field :firstname3, :size => "10" %></td>
      <td><%= f.text_field :lastname3, :size => "10" %></td>
      <td><%= f.check_box :yes3 %></td>
      <td><%= f.check_box :no3 %></td>
    </tr>
    <tr>
      <td>Guest 4:</td>
      <td><%= f.text_field :firstname4, :size => "10" %></td>
      <td><%= f.text_field :lastname4, :size => "10" %></td>
      <td><%= f.check_box :yes4 %></td>
      <td><%= f.check_box :no4 %></td>
    </tr>
    <tr>
      <td>Guest 5:</td>
      <td><%= f.text_field :firstname5, :size => "10" %></td>
      <td><%= f.text_field :lastname5, :size => "10" %></td>
      <td><%= f.check_box :yes5 %></td>
      <td><%= f.check_box :no5 %></td>
    </tr>
  </table>
  <br>
  
  <table cellpadding="5"><tr>
  <td width="300">Contact email:
  <br/><br/><%= f.text_field :email %></td>
  <td width="50"></td>
  <td width="200">Phone number:
  <br/><br/><%= f.text_field :phone %></td>
  </tr>
  </table>
  <br>
  <table width="700"><tr><td>
    Notes for Jordan and Jessie<br/>
    <%= f.text_area :notes %>
  </td></tr></table>
  
  <div>
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/rsvps/new.html.erb
<% provide(:title, 'RSVP') %>
<div id="subtitle">RSVP</div>

<div id="content">
  <div class="content-bottom">
<p>To RSVP for the wedding, please submit the form below, send us an email, or give us a call!</p>

<%= render 'form', :rsvp => @rsvp %>
  </div>
</div>

app/views/rsvps/thank_you.html.erb
<h1>Thank you!</h1>
<p>Your RSVP has been recorded</p>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/bridalparty.html.erb
<% provide(:title, 'Bridal Party') %>
<div id="subtitle">The Bridal Party</div>
<div id="content">
  <div class="content-left">
  <center>
  <%= image_tag("bianca.jpg", :width => 250) %>
  <h4>Bianca</h4><h5>Maid of Honor</h5>
  Jessie's best friend since 8th grade
  
  <br><br><br>
  <%= image_tag("geoff.jpg", :width => 250) %>
  <h4>Geoff</h4><h5>Bridesman</h5>
  Jessie's a cappella soul mate - we have a telepathic connection when it comes to music
  <br>
  <br><br><br>
  <%= image_tag("charlene.jpg", :width => 250) %>
  <h4>Charlene</h4><h5>Bridesmaid</h5>
  Jessie's first college roommate and very best friend<br> Also Jordan's college roommate... like the sister he never had
  
  <br><br><br>
  <%= image_tag("jake.jpg", :width => 250) %>
  <h4>Jake</h4><h5>Bridesman</h5>
  The best brother a sister could ask for<br>
  And the best brother-in-law Jordan could have
  <br><br><br>
  
  <%= image_tag("jessica1.jpg", :width => 250) %>
  <h4>Jessica</h4><h5>Bridesmaid</h5>
  Became best friends by spending two weeks together in Taiwan, and of course all that band and math class
  </center>
  
  </div>
  <div class="content-right">
  <center>
  
  <%= image_tag("abby.jpg", :width => 250) %>
  <h4>Abby</h4><h5>Best Man</h5>
  Jordan's college housemate and co-worker
  
  <br><br><br>
  <%= image_tag("brendan.jpg", :width => 250) %>
  <h4>Brendan</h4><h5>Groomsman</h5>
   Good friend and kindergarten classmate
  
  <br><br><br>
  <%= image_tag("marie.jpg", :width => 250) %>
  <h4>Marie</h4><h5>Groomsmaid</h5>
  Marie "You guys can never break up" Westover
  
  <br><br><br>
  <%= image_tag("andrew.jpg", :width => 250) %>
  <h4>Andrew</h4><h5>Groomsman</h5>
  Long-time friend and fellow rocketry enthusiast
  
  <br><br><br>
  <%= image_tag("pauline1.jpg", :width => 250) %>
  <h4>Pauline</h4><h5>Groomsmaid</h5>
  A great friend from Oberlin
  </center>  
  </div>

  <div class="content-bottom">
  <center>
  <%= image_tag("roxi.jpg", :width=> 250) %>
  <h4>Roxi</h4><h5>Wedding Coordinator</h5>
  Jessie's childhood best friend
  </center>
  </div>
</div>

app/views/static_pages/location.html.erb
<% provide(:title, 'Location') %>
<div id="subtitle">Location & Travel Information</div>
<div id="content">
  <div class="content-bottom"><center>
    <%= image_tag("SanDiego_panorama_resized.jpg", :alt=> "San Diego Skyline", :width=>950) %><br><br>
    Welcome to San Diego, California
    </center>
    
    <div class="minisubtitle">Transportation & Directions</div>
    <table><tr><td width = 350><center><%= image_tag("coasthwy-bridge-painted.jpg", :alt=>"Coast Highway", :width => 300) %></center>
    </td>
    
    <td width =600>Del Mar is just 20 minutes north of San Diego, or about two hours from Los Angeles - just take I-5 to Del Mar Heights Road and head west to the ocean. The <a href="http://www.san.org/">San Diego Airport</a> and <a href="http://www.gonctd.com/coaster">Coaster (local train) stations</a> are convenient transportation hubs.
    <br>
    <br>Seagrove Park is a 5 minute walk from the Powerhouse in Del Mar:
    <br>
    <br>The Del Mar Powerhouse
    <br>1658 Coast Boulevard
    <br>Del Mar, CA 92014
    <br>
    <br><u>Parking in Del Mar</u>
    <br><p>Parking should be plentiful in January, but please arrive early to make sure you are on time to the ceremony!</p>
    <ul>
    <li><b>Free residential parking</b> with no time limits in the neighborhoods north and south of the Del Mar Beach and Seagrove Park</li>
    <li><b>Seagrove Parking Lot</b> (directly across Pacific Coast Hwy from the Powerhouse) is $10 for 4 hours or $15 for 8 hours</li>
    <li><b>Public metered parking</b> available under L'Auberge for $1/hour - four-hour limit (may add time after ceremony) from 9AM-8PM</li>
    <li><b>Street metered parking</b> is $3/hour and often has a four-hour limit (free after 6PM)</li>
    <li><b>Some free Del Mar street parking</b> in the downtown area, but look out for time limits!</li>
    </td>
    </tr></table>
    
    <div class="minisubtitle">Lodging & Map</div>
    
    We are getting room blocks at three local hotels, all convenient to the wedding: the Torrey Pines/La Jolla Hilton, the Del Mar/Carmel Valley Doubletree, and Hotel Indigo in Del Mar.
    <br>
    <br>
    <ul>
      <li><%= link_to "Torrey Pines/La Jolla Hilton Reservation Website", 'http://www.hilton.com/en/hi/groups/personalized/S/SANTPHH-60L-20140103/index.jhtml?WT.mc_id=POG' %>
        <ul>
          <li>reserve by December 12th for courtesy rate</li>
        </ul>
      </li>
      <br>
      <li>Del Mar/Carmel Valley Doubletree:
        <ul>
          <li>call Emmeline Vasquez (858) 764-0261 OR</li>
          <li>email emmeline.vasquez-uk@hilton.com</li>
          <li>reserve by December 3rd for courtesy rate</li>
        </ul>
      </li>
      <br>
      <li><%= link_to "Hotel Indigo (Del Mar) Reservation Website", 'http://ichotelsgroup.com/redirect?path=rates&brandCode=IN&regionCode=1&localeCode=en&GPC=RGW&hotelCode=SANDM&_PMID=99801505' %></li>
        <ul>
          <li margin-bottom=3px>reserve online using link above (with group code RGW), or</li>
          <li>call (877) 834-3613 and ask for the Rucker/Gottdank wedding block rate, or</li>
          <li>call the hotel directly (858) 755-1501 and ask for the Rucker/Gottdank wedding block rate
          <li>reserve by December 6th for courtesy rate</li>
        </ul>
      </li>
    </ul>
    <br><br>
    
    <center>Explore the area using our customized map! Zoom out to see areas surrounding Del Mar.
    <br><br>
    <iframe width="640" height="480" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps/ms?msa=0&amp;msid=201842657862714677233.0004de6042540634c413f&amp;ie=UTF8&amp;t=m&amp;ll=32.955241,-117.258668&amp;spn=0.017285,0.027466&amp;z=15&amp;output=embed"></iframe><br /><small>View <a href="https://maps.google.com/maps/ms?msa=0&amp;msid=201842657862714677233.0004de6042540634c413f&amp;ie=UTF8&amp;t=m&amp;ll=32.955241,-117.258668&amp;spn=0.017285,0.027466&amp;z=15&amp;source=embed" style="color:#0000FF;text-align:left">Del Mar Wedding Map</a> in a larger map</small></center>
    
    <br>
    <br><u>Del Mar Lodging</u>
    <br>Hotels in Del Mar proper
    <ul>
    <!--li><%= link_to "Wave Crest", 'http://www.wavecrestresort.com/info.php?pnum=4' %> (from $150/night)</li-->
    
    <li><%= link_to "Hotel Indigo", 'http://www.hotelindigo.com/hotels/us/en/del-mar/sandm/hoteldetail?qAdlt=1&qChld=0&qRms=1&qIta=99504425&qPSt=0&qSmP=3&qWch=0&qSHp=1&qBrs=6c.cp.cv.cw.ex.hi.ic.in.rs.sb&qSrt=BRAND_SORT&qRpp=25&qFRA=1&srb_u=1&icdv=99504425&siclientid=1933&' %> (from $339/night - *$139 (1 king bed) or $159/night (2 queen bed) room block rate) - renovated in 2011, a very modern and spacious hotel with two pools and a gorgeous lobby/restaurant and views of the Pacific. Within walking distance to Del Mar.</li>
    
    <li><%= link_to "Les Artistes Inn", 'http://lesartistesinn.whizzhotels.com/' %> (from $149/night) - a fun, eclectic Del Mar hotel with ocean-view rooms and an intimate setting. Located right next to the weekend Farmer's Market, and also the closest hotel to the heart of Del Mar.</li>
    
    <li><%= link_to "Hilton Del Mar", 'http://www3.hilton.com/en/hotels/california/hilton-san-diego-del-mar-SANDMHF/index.html' %> (from $189/night) - north of downtown Del Mar and right next to the Fairgrounds. Very convenient to I-5, but also tucked away in a quiet setting.</li>
  
    <li><%= link_to "L'Auberge", 'http://www.laubergedelmar.com/' %> (from $350/night) - the ultimate vacationer's hotel. Stunning views and a very short walk to the beach, Seagrove Park, and the Powerhouse</li>
    </ul>
    <br>
    
    <u>Torrey Pines Lodging</u>
    <br>Two hotels located on the cliffs of Torrey Pines - stunning ocean views, proximity to the famous Torrey Pines Golf Course, and just a five-minute drive to Del Mar.
    <ul>
    <li><%= link_to "Torrey Pines Hilton", 'http://www.hiltonlajollatorreypines.com/' %> (from $99/night - *$94/night room block rate) - a beautiful Hilton overlooking the golf course and Pacific ocean. Please note: guest parking is $25</li>
    
    <li><%= link_to "The Lodge at Torrey Pines", 'http://www.lodgetorreypines.com/' %> (from $360/night) - right on the Torrey Pines golf course with amazing amenities and beautiful ocean views.</li>
    </ul>
    <br>
    
    <u>Carmel Valley Hotels</u>
    <br>Four hotels convenient to I-5, I-56, and a five-minute drive to Del Mar. Walking distance to local shopping centers and restaurants!
    <ul>    
    <li><%= link_to "Doubletree", 'http://www.sandiegodoubletreehotel.com/' %> (from $135/night - *$109/night room block rate) - cookies on arrival, a beautiful lobby, and a deck opening onto the hotel pool.</li>
    
    <li><%= link_to "Mariott", 'http://www.marriott.com/hotels/travel/sandm-san-diego-marriott-del-mar/' %> (from $229/night)</li>
    
    <li><%= link_to "Hampton Inn", 'http://hamptoninn3.hilton.com/en/hotels/california/hampton-inn-san-diego-del-mar-SANDLHX/index.html' %> (from $177/night)</li>

    <li><%= link_to "Residence Inn", 'http://www.marriott.com/hotels/travel/sandl-residence-inn-san-diego-del-mar' %> (from $219/night) - brand new Residence Inn servicing Carmel Valley and Del Mar.</li>
    </ul>
    <br>
   
    <u>Torrey Hills Hotels</u>
    <br>Two newer hotels, tucked away in the quiet suburbs and offices of Torrey Hills, with just a 10-minute drive to Del Mar. 
    <ul>
    <li><%= link_to "Hilton Garden Inn", 'http://hiltongardeninn3.hilton.com/en/hotels/california/hilton-garden-inn-san-diego-del-mar-SANMDGI/index.html' %> (from $138/night) - note: I have seen rates as low as $97/night, but they may not be available before January.</li>
    
    <li><%= link_to "Homewood Suites", 'http://homewoodsuites3.hilton.com/en/hotels/california/homewood-suites-by-hilton-san-diego-del-mar-SANDEHW/index.html' %> (from $113/night)</li>
    </ul>
  </div>
</div>

app/views/static_pages/photos.html.erb
<% provide(:title, 'Photos') %>
<div id="subtitle">Photos</div>

app/views/static_pages/registry.html.erb
<% provide(:title, 'Registry') %>
<div id="subtitle">Gift Registries</div>

<div id="content">
  <div class="content-bottom">
Please visit our registries online or in-store!<br><br>
<center>
<%= link_to image_tag("BBB_logo.png", alt: "Bed, Bath, & Beyond"), 'https://www.bedbathandbeyond.com/store/giftregistry/view_registry_guest.jsp?pwsToken=&eventType=Wedding&registryId=6813723&pwsurl=', :target => "_blank" %>
<br>
<%= link_to image_tag("amazonlogo.jpg", alt: "Amazon.com"), 'http://www.amazon.com/registry/wedding/1YXCQX5IZ7K62', :target => "_blank" %>
<br>
<%= link_to image_tag("cratelogo.png", alt: "Crate & Barrel"), 'http://www.crateandbarrel.com/Gift-Registry/Jessica-Rucker-and-Jordan-Gottdank/r5056996', :target => "_blank" %>
</center>
</div>
</div>

app/views/static_pages/story.html.erb
<% provide(:title, 'Our Story') %>
<div id="subtitle">Our Story</div>
<div id="content">We first met at Torrey Pines High School through the band program. While we both had close mutual friends for the first two years at Torrey, we didn't really meet until Jazz Band in our junior year... <br><br> More of the tale to come!</div>

app/views/static_pages/userlog.html.erb
    <div id="subtitle">User Login</div>
<div id="content">
  [Log in] [insert form]<br>
  or, if you don't have a username:
  <br>
  <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
  <br>
  [Forgot password]
</div>

app/views/static_pages/wedding.html.erb
<% provide(:title, '1/4/14') %>

<div id="subtitle"><table><tr><td style="vertical-align:middle">We're getting married, and we hope you'll be there - 1/4/14</td></tr></table><%= image_tag("Transparent.gif", :height => '30px') %></div>

<%= image_tag("tree7.jpg", alt: "Del Mar, California", :id => "bgimage", :width => "100%" ) %>
<br>
<div id="content">
<div class="content-bottom">
  <div class="minisubtitle">Announcements</div>
  <b>December 26th, 2013</b>
  <p>The wedding is just over a week away! Here are your FAQs:</p>
  <ol>
  <li><b>What should I wear to the wedding?</b></li>
  Semi-formal attire is suggested.
  <br>
  <li><b>When is dinner served?</b></li>
  Cocktail hour is at 3PM. Dinner will start at approximately 4:15PM
  <br>
  <li><b>Where is convenient to park in Del Mar?</b></li>
  See the <%= link_to "location", location_path %> page for parking information.
  <br>
  <li><b>What is Del Mar weather like?</b></li>
  Right now the weather forecast suggests a high of 71 degrees with partial clouds.
  <br>
  </ol>
  See you soon!<br><br>
  
  <b>October 22nd, 2013</b>
  <p>We're having a beach bonfire on January 1st at La Jolla! If you are in town, please join us for this San Diego winter tradition. More information on the <%= link_to "Wedding", weddingday_path %> page</p>
  
  <b>August 26th, 2013</b>
  <p>Invitations have been mailed! Kindly respond by November 23rd, using the form on the RSVP page.</p>
  <b>June 1st, 2013</b>
  <p>Welcome to our wedding website! Please browse the links at the top to learn more about us and our wedding.</p>
</div>
</div>

app/views/static_pages/weddingday.html.erb
<% provide(:title, 'Wedding') %>
<div id="subtitle">Wedding Events</div>
<div id="content">
Our wedding is on Saturday, January 4th, 2014. See below for details of the day.
<br><br>
All guests are also invited to:
<ul>
<li><b>January 1st Evening Beach Bonfire Potluck</b> at La Jolla Shores! Let's meet around 4PM while the sun is still up - bring beach blankets and chairs, and something yummy for dinner or s'mores (and let everyone else know what you are bringing: <a href="https://docs.google.com/spreadsheet/ccc?key=0AjGGpunHTkhIdGpaSWxrVjJsQmhUT3hOdE8yTVViRVE&usp=sharing">post it here</a>)</li>
<li><b>Wedding Afterparty</b>, January 4th around 9PM (location TBA)</li>
</ul>
<br>

<div class="minisubtitle">Our Big Day</div>
<%= image_tag("seagrove-park-sign_compressed.jpg", :alt => "Seagrove Park", :width => 450) %>
<%= image_tag("seagrove-park-walkway_compressed.jpg", :alt => "A Del Mar park overlooking the Pacific", :width => 450) %>

<br><br>
<center>
Wedding Ceremony
<br>to be held outisde at
<br><h3>Seagrove Park</h3>
2:14PM
<br><br>
<br>Reception to follow at
<br><h3>the Powerhouse in Del Mar</h3>
3-8PM
<br>
<br>3:00PM Cocktail Hour
<br>4:15PM Dinner and Dancing
</center>
<br><br>

<%= image_tag("powerhouse-oceanview_compressed.jpg", :alt => "The Powerhouse is right by the ocean", :width =>425) %>
<%= image_tag("powerhouse-topview_compressed.jpg", :alt => "A historic Del Mar landmark", :width => 475) %>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div id="subtitle">My Account</div>
<div class="row">
  <aside class="span4">
    <section>
      <div id="content">
        <%= gravatar_for @user %>
        <%= @user.name %>
      </div>
    </section>
  </aside>
</div>